# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 01:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='pic',
            new_name='image',
        ),
    ]
